#!/usr/bin/zsh

# Usage: `source theme-switch (light|dark)?`. Defaults to light.
# sed command to substitute to appropriate theme in alacritty config

theme=$argv[1]
if [[ $theme == "dark" ]]
then
    echo 'Switching to Dark Theme'
    sed -i 's/\*light/\*dark/g' ~/.config/alacritty/alacritty.yml
else
    theme="light"
    echo 'Switching to Light Theme'
    sed -i 's/\*dark/\*light/g' ~/.config/alacritty/alacritty.yml
fi

echo "--theme=\"gruvbox-$theme\"" > ~/.config/bat/config
export THEME_CONTEXT="$1"
